[package]
name = "macro-ruby"
version = "1.1.1"
edition = "2018"
description = "Execute ruby code at compile time trough mruby"
repository = "https://github.com/DumbMahreeo/macro-ruby"
license = "MIT"

[lib]
proc-macro = true

[dependencies]

[features]
yarv = []
full = []
